### ISSUE TITLE
KeyError: 'VIDEO'

### ISSUE THREAD

**Issue by ghost** [BasioMeusPuga/twitchy#18]
```$ twitchy
Traceback (most recent call last):
  File "/usr/bin/twitchy", line 11, in <module>
    load_entry_point('twitchy==3.2.0', 'console_scripts', 'twitchy')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/twitchy/__main__.py", line 16, in <module>
    from twitchy import twitchy_database
  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_database.py", line 7, in <module>
    from twitchy import twitchy_api
  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_api.py", line 13, in <module>
    Options.parse_options()
  File "/usr/lib/python3.6/site-packages/twitchy/twitchy_config.py", line 193, in parse_options
    video_section = config['VIDEO']
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'VIDEO' ```

**Comment by ghost** [comment]
I'd like to add that I'm on Python 3.6.4 and Linux Zen 4.14.11
I did try deleting my ~/.config/twitchy3

**Comment by BasioMeusPuga** [comment]
This honestly just stopped working by itself. I've changed nothing in that file for months. I don't even...

Nevertheless, it should be fixed now.

**Comment by wigust** [comment]
Hello @BasioMeusPuga 

Seems `~/.config/twitchy3/twitchy.cfg` doesn't exist during `python setup.py test`.  Could you look at?

**Comment by BasioMeusPuga** [comment]
@wigust 
Hey. You're supposed to run `twitchy` in the terminal first. The file gets created in the `~/.config/twitchy3/` directory along with the database.
I can't include it elsewhere because it requires user input at first run.

**Comment by wigust** [comment]
Tests suite fails because of that.  Could you generate or put a static config example for test?

I package Twitchy for [Guix](https://www.gnu.org/software/guix/).  We test all Python packages by default.  I think other distributions do the same, too.

**Comment by BasioMeusPuga** [comment]
Sure. Give me a little bit of time. I'll message when it's done.

**Comment by BasioMeusPuga** [comment]
I've pushed a commit that creates a temporary config file. See if it works for your purposes?

**Comment by wigust** [comment]
Apologies for a long response.

```
running "python setup.py" with command "test" and parameters ()
 Configure:
 Media player [mpv]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 11, in <module>
    twitchy_config.ConfigInit(True)
  File "/tmp/guix-build-twitchy-3.2.drv-0/source/twitchy/twitchy_config.py", line 61, in __init__
    self.configure_options()
  File "/tmp/guix-build-twitchy-3.2.drv-0/source/twitchy/twitchy_config.py", line 70, in configure_options
    self.player = input(' Media player [mpv]: ')
EOFError: EOF when reading a line
```

As I see, `input(' Media player [mpv]: ')` is an interactive function.  Could you make it please non-interactive, because package builders cannot do interactive things?

**Comment by BasioMeusPuga** [comment]
I can't make that non-interactive. That would defeat the entire purpose of the config wizard. I can, however, handle that exception so that a default value gets passed to the config file. Will that do?

**Comment by wigust** [comment]
I think it will.  Thank you!

**Comment by BasioMeusPuga** [comment]
I've pushed a commit to do just that. Please let me know if it works correctly.

**Comment by wigust** [comment]
0c0f925b9c7ff2aed4a3b0046561cb794143c398 build succeeded.  I'll send a patch to a Guix package collection for a review.  Thank you.
