### ISSUE TITLE
SyntaxError: invalid syntax on launch

### ISSUE THREAD

**Issue by Orgams** [BasioMeusPuga/twitchy#39]
Hello,

After executing :
```
python setup.py build
python setup.py install
```

on launch "twitchy" i have :
``` Traceback (most recent call last):
  File "/usr/local/bin/twitchy", line 11, in <module>
    load_entry_point('twitchy==3.4.0', 'console_scripts', 'twitchy')()
  File "/home/orgams/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/orgams/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/orgams/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/orgams/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/twitchy-3.4.0-py2.7.egg/twitchy/__main__.py", line 100
    f' Delete {Colors.YELLOW + i + Colors.ENDC} (y/N) ')
```

I'm novice with Python, you have a idea ?

**Comment by blazingkin** [comment]
Hi, this is probably because `python` is setup to run python 2 on your system. This looks like its a python 3 script.

Try running with `python3`
